C      INCLUDE 'emmix/EMD.f'
C      INCLUDE 'emmix/EMFAC.f'
       INCLUDE 'emmix/EMMIX.f'
C      INCLUDE 'emmix/EMMIX-f1.f'
C      INCLUDE 'emmix/EMMIX-f2.f'
C      INCLUDE 'emmix/EMMIX-spher.f'
C      INCLUDE 'emmix/EMMIX-t.f'
C      INCLUDE 'emmix/EMMIX-t.f'
C      INCLUDE 'emmix/EMFAC.max'
C      INCLUDE 'emmix/EMMIX.max'
C      INCLUDE 'emmix/EMMIX-f1.max'
C      INCLUDE 'emmix/EMMIX-f2.max'
C      INCLUDE 'emmix/EMMIX-spher.max'
C      INCLUDE 'emmix/EMMIX-t.max'
C      INCLUDE 'emmix/EMMIX-t.max'
