# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp sourceCpp
#'@useDynLib EMMIXgene
NULL

emmix_t <- function(dat) {
    .Call('_EMMIXgene_emmix_t', PACKAGE = 'EMMIXgene', dat)
}

#'@importFrom Rcpp sourceCpp
#'@useDynLib EMMIXgene
NULL

call_emmix_sel <- function(t, row, col, g) {
    .Call('_EMMIXgene_call_emmix_sel', PACKAGE = 'EMMIXgene', t, row, col, g)
}

select_genes <- function(data, row, col, g, k, r, b1, b2) {
    .Call('_EMMIXgene_select_genes', PACKAGE = 'EMMIXgene', data, row, col, g, k, r, b1, b2)
}

