# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp sourceCpp
NULL

estep <- function(dat, params) {
    .Call('_EMMIXgene_estep', PACKAGE = 'EMMIXgene', dat, params)
}

mstep <- function(dat, tau, you, params) {
    .Call('_EMMIXgene_mstep', PACKAGE = 'EMMIXgene', dat, tau, you, params)
}

emmix_t <- function(dat, params, g = 1L, max_it = 100L) {
    .Call('_EMMIXgene_emmix_t', PACKAGE = 'EMMIXgene', dat, params, g, max_it)
}

